default: &default
  dispatchers:
    - polling_interval: <%= ENV.fetch("QUEUE_DISPATCHER_POLLING_INTERVAL", 1) %>
      batch_size: <%= ENV.fetch("QUEUE_DISPATCHER_BATCH_SIZE", 500) %>
  workers:
    - queues: default
      threads: <%= ENV.fetch("JOB_THREADS", 3) %>
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: <%= ENV.fetch("QUEUE_WORKER_POLLING_INTERVAL", 0.5) %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
