class AddRemainingFieldsToPitchData < ActiveRecord::Migration[7.1]
  def change
    add_column :pitch_data, :balls, :integer
    add_column :pitch_data, :strikes, :integer
    add_column :pitch_data, :outs_when_up, :integer
    add_column :pitch_data, :release_speed, :float
    add_column :pitch_data, :release_spin_rate, :float
    add_column :pitch_data, :release_extension, :float
    add_column :pitch_data, :release_pos_x, :float
    add_column :pitch_data, :release_pos_y, :float
    add_column :pitch_data, :release_pos_z, :float
    add_column :pitch_data, :pfx_x, :float
    add_column :pitch_data, :pfx_z, :float
    add_column :pitch_data, :plate_x, :float
    add_column :pitch_data, :plate_z, :float
    add_column :pitch_data, :zone, :integer
    add_column :pitch_data, :launch_speed, :float
    add_column :pitch_data, :launch_angle, :float
    add_column :pitch_data, :hit_distance_sc, :float
    add_column :pitch_data, :bb_type, :string
    add_column :pitch_data, :estimated_ba_using_speedangle, :float
    add_column :pitch_data, :estimated_woba_using_speedangle, :float
    add_column :pitch_data, :woba_value, :float
    add_column :pitch_data, :delta_run_exp, :float
    add_column :pitch_data, :bat_score, :integer
    add_column :pitch_data, :fld_score, :integer
    add_column :pitch_data, :post_bat_score, :integer
    add_column :pitch_data, :post_fld_score, :integer
    add_column :pitch_data, :sv_id, :string
    add_column :pitch_data, :age_bat, :float
    add_column :pitch_data, :age_bat_legacy, :float
    add_column :pitch_data, :age_pit, :float
    add_column :pitch_data, :age_pit_legacy, :float
    add_column :pitch_data, :api_break_x_arm, :float
    add_column :pitch_data, :api_break_x_batter_in, :float
    add_column :pitch_data, :api_break_z_with_gravity, :float
    add_column :pitch_data, :arm_angle, :float
    add_column :pitch_data, :attack_angle, :float
    add_column :pitch_data, :attack_direction, :float
    add_column :pitch_data, :away_score, :integer
    add_column :pitch_data, :ax, :float
    add_column :pitch_data, :ay, :float
    add_column :pitch_data, :az, :float
    add_column :pitch_data, :babip_value, :float
    add_column :pitch_data, :bat_score_diff, :integer
    add_column :pitch_data, :bat_speed, :float
    add_column :pitch_data, :bat_win_exp, :float
    add_column :pitch_data, :batter_days_since_prev_game, :integer
    add_column :pitch_data, :batter_days_until_next_game, :integer
    add_column :pitch_data, :break_angle_deprecated, :float
    add_column :pitch_data, :break_length_deprecated, :float
    add_column :pitch_data, :delta_home_win_exp, :float
    add_column :pitch_data, :delta_pitcher_run_exp, :float
    add_column :pitch_data, :des, :string
    add_column :pitch_data, :effective_speed, :float
    add_column :pitch_data, :estimated_slg_using_speedangle, :float
    add_column :pitch_data, :fielder_2, :bigint
    add_column :pitch_data, :fielder_3, :bigint
    add_column :pitch_data, :fielder_4, :bigint
    add_column :pitch_data, :fielder_5, :bigint
    add_column :pitch_data, :fielder_6, :bigint
    add_column :pitch_data, :fielder_7, :bigint
    add_column :pitch_data, :fielder_8, :bigint
    add_column :pitch_data, :fielder_9, :bigint
    add_column :pitch_data, :game_year, :integer
    add_column :pitch_data, :hc_x, :float
    add_column :pitch_data, :hc_y, :float
    add_column :pitch_data, :hit_location, :integer
    add_column :pitch_data, :home_score, :integer
    add_column :pitch_data, :home_score_diff, :integer
    add_column :pitch_data, :home_win_exp, :float
    add_column :pitch_data, :hyper_speed, :float
    add_column :pitch_data, :if_fielding_alignment, :string
    add_column :pitch_data, :intercept_ball_minus_batter_pos_x_inches, :float
    add_column :pitch_data, :intercept_ball_minus_batter_pos_y_inches, :float
    add_column :pitch_data, :iso_value, :float
    add_column :pitch_data, :launch_speed_angle, :integer
    add_column :pitch_data, :miss_distance, :float
    add_column :pitch_data, :n_priorpa_thisgame_player_at_bat, :integer
    add_column :pitch_data, :n_thruorder_pitcher, :integer
    add_column :pitch_data, :of_fielding_alignment, :string
    add_column :pitch_data, :on_1b, :bigint
    add_column :pitch_data, :on_2b, :bigint
    add_column :pitch_data, :on_3b, :bigint
    add_column :pitch_data, :pitcher_days_since_prev_game, :integer
    add_column :pitch_data, :pitcher_days_until_next_game, :integer
    add_column :pitch_data, :post_away_score, :integer
    add_column :pitch_data, :post_home_score, :integer
    add_column :pitch_data, :spin_axis, :float
    add_column :pitch_data, :spin_dir, :float
    add_column :pitch_data, :spin_rate_deprecated, :float
    add_column :pitch_data, :swing_length, :float
    add_column :pitch_data, :swing_path_tilt, :float
    add_column :pitch_data, :sz_bot, :float
    add_column :pitch_data, :sz_top, :float
    add_column :pitch_data, :tfs_deprecated, :string
    add_column :pitch_data, :tfs_zulu_deprecated, :string
    add_column :pitch_data, :type, :string
    add_column :pitch_data, :umpire, :bigint
    add_column :pitch_data, :vx0, :float
    add_column :pitch_data, :vy0, :float
    add_column :pitch_data, :vz0, :float
    add_column :pitch_data, :woba_denom, :integer
  end
end
